version: "3.8"
services:
  backend:
    container_name: backend
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
