version: "3.8"
services:
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/backend
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  frontend:
    container_name: frontend
    image: node:10.22.0-alpine
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
    env_file:
      - .env
    depends_on:
      - backend
      - db

volumes:
  postgres_data:
