version: '2.1'
services:
  dancefest-backend:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/dancefest-backend
    env_file:
        - .env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=dancefest
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=ansonyu

volumes:
  postgres_data:
