"""modify nomination comments table

Revision ID: 920b33a546fd
Revises: 0c66ca773c8e
Create Date: 2019-07-18 22:58:07.432762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920b33a546fd'
down_revision = 'dedc17d321a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nomination_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adjudication_id', sa.Integer(), nullable=True),
    sa.Column('award_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['adjudication_id'], ['adjudication.id'], ),
    sa.ForeignKeyConstraint(['award_id'], ['award.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('nomination_comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nomination_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('adjudication_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('award_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['adjudication_id'], ['adjudication.id'], name='nomination_comments_adjudication_id_fkey'),
    sa.ForeignKeyConstraint(['award_id'], ['award.id'], name='nomination_comments_award_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='nomination_comments_pkey')
    )
    op.drop_table('nomination_comment')
    # ### end Alembic commands ###
