"""add token to school table

Revision ID: dedc17d321a6
Revises: 0c66ca773c8e
Create Date: 2019-07-21 18:10:13.455506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedc17d321a6'
down_revision = '0c66ca773c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'token')
    # ### end Alembic commands ###
