"""add nominee count

Revision ID: 865c1b1217b0
Revises: b2976568d1c3
Create Date: 2019-07-28 23:07:54.833845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865c1b1217b0'
down_revision = 'b2976568d1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award', sa.Column('nominee_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('award', 'nominee_count')
    # ### end Alembic commands ###
