"""empty message

Revision ID: 922efec45a2b
Revises: 0c66ca773c8e
Create Date: 2019-07-19 15:21:01.118649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922efec45a2b'
down_revision = '0c66ca773c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tablet_serial'), 'tablet', ['serial'], unique=True)
    op.create_foreign_key('adj.tab.id.fk', 'adjudication', 'tablet', ['tablet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('adj.tab.id.fk', 'adjudication', type_='foreignkey')
    op.drop_index(op.f('ix_tablet_serial'), table_name='tablet')
    op.drop_table('tablet')
    # ### end Alembic commands ###
