name: Dancefest CI Checks

on:
  push:
    branches: [master, staging, dev]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master, staging, dev]

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: .
        run: yarn install
      - name: Linting Prettier
        working-directory: .
        run: |
          yarn lint:prettier
      - name: Linting ESlint
        working-directory: .
        run: |
          yarn lint:eslint
      # Test with Jest
