name: Deploy Dancefest Production Website
on:
  push:
    branches: [master]
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: dancefest-production
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'dancefest-prod'
          heroku_email: 'dancefest@uwblueprint.org'
